-- OLFU CCS Competition Tabulation System: apply through Supabase SQL editor or CLI.
create extension if not exists pgcrypto;
create type public.user_role as enum ('admin','judge','viewer');
create type public.record_status as enum ('draft','registration_open','ongoing','scoring','finalizing','finalized','published','archived');
create table public.profiles (id uuid primary key default gen_random_uuid(), auth_user_id uuid not null unique references auth.users(id) on delete cascade, full_name text not null check (length(trim(full_name)) between 2 and 80 and full_name ~ '[A-Za-z]'), email text not null unique check (email = lower(email)), judge_id text unique check (judge_id ~ '^[A-Za-z0-9/_-]{3,40}$'), contact_number text check (contact_number ~ '^\+639[0-9]{9}$'), role public.user_role not null default 'judge', status text not null default 'pending' check (status in ('pending','active','suspended')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.competitions (id uuid primary key default gen_random_uuid(), name text not null check (length(trim(name)) > 2), description text, academic_year text not null, start_date date not null, end_date date not null check(end_date >= start_date), status public.record_status not null default 'draft', created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.events (id uuid primary key default gen_random_uuid(), competition_id uuid not null references public.competitions(id) on delete cascade, name text not null, description text, event_type text not null, participation_type text not null check(participation_type in ('individual','team')), status public.record_status not null default 'draft', start_at timestamptz, end_at timestamptz check(end_at is null or start_at is null or end_at >= start_at), max_participants integer check(max_participants > 0), created_by uuid references public.profiles(id), unique(competition_id,name));
create table public.contestants (id uuid primary key default gen_random_uuid(), contestant_number text not null, full_name text not null check(length(trim(full_name)) > 1), student_id text, course text not null, year_level text check(year_level in ('1st Year','2nd Year','3rd Year','4th Year')), section text, contact_information text, status text not null default 'registered' check(status in ('registered','confirmed','checked_in','competing','disqualified','withdrawn','completed')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.event_contestants (id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade, contestant_id uuid not null references public.contestants(id) on delete cascade, registration_status text not null default 'registered', unique(event_id,contestant_id));
create table public.teams (id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade, team_number text not null, team_name text not null, status text not null default 'registered', unique(event_id,team_number), unique(event_id,team_name));
create table public.team_members (team_id uuid references public.teams(id) on delete cascade, contestant_id uuid references public.contestants(id) on delete cascade, primary key(team_id,contestant_id));
create table public.judge_event_assignments (id uuid primary key default gen_random_uuid(), judge_id uuid not null references public.profiles(id) on delete cascade, event_id uuid not null references public.events(id) on delete cascade, assigned_at timestamptz not null default now(), status text not null default 'active', unique(judge_id,event_id));
create table public.criteria (id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade, name text not null check(length(trim(name)) > 0), description text, weight_percentage numeric(5,2) not null check(weight_percentage > 0 and weight_percentage <= 100), max_score numeric(8,2) not null check(max_score > 0), display_order integer not null check(display_order >= 0), is_locked boolean not null default false, created_by uuid references public.profiles(id), unique(event_id,display_order));
create unique index criteria_unique_name_per_event on public.criteria(event_id, lower(name));
create table public.score_sheets (id uuid primary key default gen_random_uuid(), judge_id uuid not null references public.profiles(id), event_id uuid not null references public.events(id), status text not null default 'draft' check(status in ('draft','submitted','reopened')), submitted_at timestamptz, submitted_by uuid references public.profiles(id), unique(judge_id,event_id));
create table public.scores (id uuid primary key default gen_random_uuid(), judge_id uuid not null references public.profiles(id), event_id uuid not null references public.events(id), contestant_id uuid not null references public.contestants(id), criterion_id uuid not null references public.criteria(id), raw_score numeric(8,2) not null check(raw_score >= 0), weighted_score numeric(10,4) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(judge_id,event_id,contestant_id,criterion_id));
create table public.results (id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade, contestant_id uuid not null references public.contestants(id), final_score numeric(10,4) not null, rank integer, status text not null default 'provisional', finalized_at timestamptz, finalized_by uuid references public.profiles(id), unique(event_id,contestant_id));
create table public.winners (id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade, contestant_id uuid not null references public.contestants(id), placement integer not null check(placement > 0), title text not null, final_score numeric(10,4) not null, confirmed_at timestamptz, confirmed_by uuid references public.profiles(id), unique(event_id,placement));
create table public.tie_breakers (id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade, criterion_id uuid not null references public.criteria(id), priority integer not null check(priority > 0), unique(event_id,priority));
create table public.audit_logs (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, old_value jsonb, new_value jsonb, created_at timestamptz not null default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (auth_user_id, full_name, email, judge_id, contact_number, role, status) values (new.id, trim(coalesce(new.raw_user_meta_data->>'full_name','')), lower(new.email), nullif(trim(new.raw_user_meta_data->>'judge_id'),''), nullif(trim(new.raw_user_meta_data->>'contact_number'),''), 'judge', 'pending'); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.current_profile_id() returns uuid language sql stable security definer set search_path = public as $$ select id from public.profiles where auth_user_id = auth.uid() $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin' and status = 'active') $$;
create or replace function public.is_assigned(event_uuid uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.judge_event_assignments where judge_id = public.current_profile_id() and event_id = event_uuid and status = 'active') $$;
create or replace function public.score_before_write() returns trigger language plpgsql security definer set search_path = public as $$ declare c public.criteria; begin select * into c from public.criteria where id = new.criterion_id and event_id = new.event_id; if not found then raise exception 'Criterion does not belong to this event'; end if; if new.raw_score > c.max_score then raise exception 'Score exceeds maximum score'; end if; if c.is_locked = false then raise exception 'Scoring cannot begin until criteria are locked'; end if; if exists(select 1 from public.score_sheets where judge_id = new.judge_id and event_id = new.event_id and status = 'submitted') then raise exception 'Submitted score sheets cannot be modified'; end if; new.weighted_score := round(new.raw_score * c.weight_percentage / 100, 4); return new; end $$;
create trigger score_before_write before insert or update on public.scores for each row execute function public.score_before_write();
create or replace function public.criteria_before_update() returns trigger language plpgsql security definer set search_path = public as $$ begin if old.is_locked and not public.is_admin() then raise exception 'Only an administrator can unlock criteria'; end if; if old.is_locked and new.is_locked = false and not public.is_admin() then raise exception 'Only an administrator can unlock criteria'; end if; if exists(select 1 from public.scores where criterion_id=old.id) and (new.name,new.description,new.weight_percentage,new.max_score,new.display_order) is distinct from (old.name,old.description,old.weight_percentage,old.max_score,old.display_order) then raise exception 'Criteria cannot change after scores exist'; end if; return new; end $$;
create trigger criteria_before_update before update on public.criteria for each row execute function public.criteria_before_update();
create or replace function public.lock_criteria_for_scoring(event_uuid uuid) returns void language plpgsql security definer set search_path = public as $$ begin if not public.is_admin() and not public.is_assigned(event_uuid) then raise exception 'Not authorized'; end if; if (select coalesce(sum(weight_percentage),0) from public.criteria where event_id=event_uuid) <> 100 then raise exception 'Criteria weights must total exactly 100'; end if; update public.criteria set is_locked=true where event_id=event_uuid; update public.events set status='scoring' where id=event_uuid; end $$;
create or replace function public.refresh_event_results(event_uuid uuid) returns void language plpgsql security definer set search_path = public as $$ begin insert into public.results(event_id,contestant_id,final_score,rank) select event_uuid, totals.contestant_id, totals.final_score, rank() over(order by totals.final_score desc) from (select s.contestant_id, round(avg(s.judge_total),4) final_score from (select judge_id, contestant_id, sum(weighted_score) judge_total from public.scores where event_id=event_uuid group by judge_id, contestant_id) s join public.score_sheets sh on sh.judge_id=s.judge_id and sh.event_id=event_uuid and sh.status='submitted' group by s.contestant_id) totals on conflict(event_id,contestant_id) do update set final_score=excluded.final_score,rank=excluded.rank; end $$;
create or replace function public.submit_score_sheet(event_uuid uuid) returns void language plpgsql security definer set search_path = public as $$ declare missing_count integer; begin select count(*) into missing_count from public.event_contestants ec cross join public.criteria c where ec.event_id=event_uuid and c.event_id=event_uuid and not exists(select 1 from public.scores s where s.event_id=event_uuid and s.judge_id=public.current_profile_id() and s.contestant_id=ec.contestant_id and s.criterion_id=c.id); if missing_count > 0 then raise exception 'Score sheet cannot be submitted: % score(s) are missing', missing_count; end if; insert into public.score_sheets(judge_id,event_id,status,submitted_at,submitted_by) values(public.current_profile_id(),event_uuid,'submitted',now(),public.current_profile_id()) on conflict(judge_id,event_id) do update set status='submitted',submitted_at=now(),submitted_by=public.current_profile_id(); perform public.refresh_event_results(event_uuid); end $$;

alter table public.profiles enable row level security; alter table public.competitions enable row level security; alter table public.events enable row level security; alter table public.contestants enable row level security; alter table public.event_contestants enable row level security; alter table public.teams enable row level security; alter table public.team_members enable row level security; alter table public.judge_event_assignments enable row level security; alter table public.criteria enable row level security; alter table public.scores enable row level security; alter table public.score_sheets enable row level security; alter table public.results enable row level security; alter table public.winners enable row level security; alter table public.audit_logs enable row level security;
create policy "profile own or admin" on public.profiles for select using (auth_user_id=auth.uid() or public.is_admin()); create policy "profile registration" on public.profiles for insert with check(auth_user_id=auth.uid()); create policy "profile admin update" on public.profiles for update using(public.is_admin());
create policy "admin all competitions" on public.competitions for all using(public.is_admin()) with check(public.is_admin()); create policy "admin all events" on public.events for all using(public.is_admin()) with check(public.is_admin()); create policy "judge assigned events" on public.events for select using(public.is_assigned(id));
create policy "admin contestants" on public.contestants for all using(public.is_admin()) with check(public.is_admin()); create policy "judge contestants" on public.contestants for select using(exists(select 1 from public.event_contestants ec where ec.contestant_id=id and public.is_assigned(ec.event_id)));
create policy "event contestants admin" on public.event_contestants for all using(public.is_admin()) with check(public.is_admin()); create policy "event contestants judge view" on public.event_contestants for select using(public.is_assigned(event_id));
create policy "teams admin" on public.teams for all using(public.is_admin()) with check(public.is_admin()); create policy "teams judge view" on public.teams for select using(public.is_assigned(event_id)); create policy "team members admin" on public.team_members for all using(public.is_admin()) with check(public.is_admin()); create policy "team members judge view" on public.team_members for select using(exists(select 1 from public.teams t where t.id=team_id and public.is_assigned(t.event_id)));
create policy "admin assignments" on public.judge_event_assignments for all using(public.is_admin()) with check(public.is_admin()); create policy "judge assignments" on public.judge_event_assignments for select using(judge_id=public.current_profile_id());
create policy "criteria assigned select" on public.criteria for select using(public.is_admin() or public.is_assigned(event_id)); create policy "criteria create assigned" on public.criteria for insert with check((public.is_admin() or public.is_assigned(event_id)) and created_by=public.current_profile_id()); create policy "criteria edit assigned" on public.criteria for update using((public.is_admin() or public.is_assigned(event_id)) and not is_locked);
create policy "scores own" on public.scores for all using(judge_id=public.current_profile_id() or public.is_admin()) with check(judge_id=public.current_profile_id() or public.is_admin()); create policy "sheets own" on public.score_sheets for all using(judge_id=public.current_profile_id() or public.is_admin()) with check(judge_id=public.current_profile_id() or public.is_admin());
create policy "tie breakers admin" on public.tie_breakers for all using(public.is_admin()) with check(public.is_admin()); create policy "tie breakers judge view" on public.tie_breakers for select using(public.is_assigned(event_id));
create policy "public published events" on public.events for select using(status='published'); create policy "public published results" on public.results for select using(exists(select 1 from public.events e where e.id=event_id and e.status='published') or public.is_admin()); create policy "public published winners" on public.winners for select using(exists(select 1 from public.events e where e.id=event_id and e.status='published') or public.is_admin()); create policy "admin results" on public.results for all using(public.is_admin()) with check(public.is_admin()); create policy "admin winners" on public.winners for all using(public.is_admin()) with check(public.is_admin()); create policy "admin audit" on public.audit_logs for select using(public.is_admin());

create or replace function public.audit_row_change() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.audit_logs(user_id,action,entity_type,entity_id,old_value,new_value) values (public.current_profile_id(), lower(tg_op), tg_table_name, coalesce(new.id,old.id), case when tg_op='INSERT' then null else to_jsonb(old) end, case when tg_op='DELETE' then null else to_jsonb(new) end); return coalesce(new,old); end $$;
create trigger audit_competitions after insert or update or delete on public.competitions for each row execute function public.audit_row_change(); create trigger audit_events after insert or update or delete on public.events for each row execute function public.audit_row_change(); create trigger audit_contestants after insert or update or delete on public.contestants for each row execute function public.audit_row_change(); create trigger audit_assignments after insert or update or delete on public.judge_event_assignments for each row execute function public.audit_row_change(); create trigger audit_criteria after insert or update or delete on public.criteria for each row execute function public.audit_row_change(); create trigger audit_scores after insert or update or delete on public.scores for each row execute function public.audit_row_change(); create trigger audit_sheets after insert or update or delete on public.score_sheets for each row execute function public.audit_row_change(); create trigger audit_winners after insert or update or delete on public.winners for each row execute function public.audit_row_change();
